define([
    './touchHome',
    './traineeQuery',
    './touchLogin',
    './main',
    './trainee',
    './traineeCalendar',
    './traineeHistory',
    './traineeMain',
    './traineeHome',
    './traineeLogin',
    './traineeRegister',
    './traineeEvaluation',
    './traineeProfile',
    './traineePassword',
    './coachLogin',
    './coachTrainee',
    './coachTraineeHome',
    './traineeMovements',
    './traineeReport',
    './base',
    './coachPassword',
    './traineeList',
    './traineeNew',
    './touchTrainee',
    './coachManagement',
    './coachProfile',
    './settings',
    './touchTraineeHome',
    './traineeEndTrain',
    './sportEvent',
    './traineeSelect'
], function(){});


